/*DROP DATABASE IF EXISTS MettingOnTime_db;
CREATE DATABASE MettingOnTime_db;*/

USE MettingOnTime_db;

-- Supprimer les contraintes de clé étrangère en double
ALTER TABLE Possèder DROP FOREIGN KEY FK_Possèder_id_USER;
ALTER TABLE Possèder DROP FOREIGN KEY FK_Possèder_id_SPECIALISTE;

ALTER TABLE Prendre DROP FOREIGN KEY FK_Prendre_id_USER;
ALTER TABLE Prendre DROP FOREIGN KEY FK_Prendre_id_SPECIALISTE;
ALTER TABLE Prendre DROP FOREIGN KEY FK_Prendre_id_RENDEZ_VOUS;

ALTER TABLE Localiser DROP FOREIGN KEY FK_Localiser_id_ADRESSE;
ALTER TABLE Localiser DROP FOREIGN KEY FK_Localiser_id_USER;

ALTER TABLE USER DROP FOREIGN KEY FK_USER_id_PERMISSION;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    id_USER INT AUTO_INCREMENT NOT NULL,
    first_name_USER VARCHAR(255),
    last_name_USER VARCHAR(255),
    num_phone_USER INT NOT NULL,
    email_USER VARCHAR(255) NOT NULL,
    dt_created_USER DATETIME NOT NULL,
    id_PERMISSION INT NOT NULL,
    PRIMARY KEY (id_USER),
    CONSTRAINT FK_USER_id_PERMISSION FOREIGN KEY (id_PERMISSION) REFERENCES PERMISSION (id_PERMISSION) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS PERMISSION;
CREATE TABLE PERMISSION (
    id_PERMISSION INT AUTO_INCREMENT NOT NULL,
    statut_PERMISSION VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_PERMISSION)
);

DROP TABLE IF EXISTS RENDEZ_VOUS;
CREATE TABLE RENDEZ_VOUS (
    id_RENDEZ_VOUS INT AUTO_INCREMENT NOT NULL,
    title_RENDEZ_VOUS VARCHAR(255) NOT NULL,
    dt_time_start_RENDEZ_VOUS DATETIME NOT NULL,
    duration_RENDEZ_VOUS TIME NOT NULL,
    confirm BOOLEAN NOT NULL,
    content_RENDEZ_VOUS TEXT NOT NULL,
    dt_created_RENDEZ_VOUS DATETIME NOT NULL,
    PRIMARY KEY (id_RENDEZ_VOUS)
);

DROP TABLE IF EXISTS SPECIALITE;
CREATE TABLE SPECIALITE (
    id_SPECIALISTE INT AUTO_INCREMENT NOT NULL,
    tilte_SPECIALITES VARCHAR(255) NOT NULL,
    decription_SPECIALISTE TEXT NOT NULL,
    PRIMARY KEY (id_SPECIALISTE)
);

DROP TABLE IF EXISTS ADRESSE;
CREATE TABLE ADRESSE (
    id_ADRESSE INT AUTO_INCREMENT NOT NULL,
    num_rue_Adresse INT NOT NULL,
    rue_Adresse VARCHAR(255),
    code_postale_Adresse VARCHAR(255),
    Ville_Adresse VARCHAR(255),
    pays_Adresse VARCHAR(255),
    PRIMARY KEY (id_ADRESSE)
);

DROP TABLE IF EXISTS Prendre;
CREATE TABLE Prendre (
    id_USER INT NOT NULL,
    id_SPECIALISTE INT NOT NULL,
    id_RENDEZ_VOUS INT NOT NULL,
    PRIMARY KEY (id_USER, id_SPECIALISTE, id_RENDEZ_VOUS),
    CONSTRAINT FK_Prendre_id_USER FOREIGN KEY (id_USER) REFERENCES USER (id_USER) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Prendre_id_SPECIALISTE FOREIGN KEY (id_SPECIALISTE) REFERENCES SPECIALITE (id_SPECIALISTE) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Prendre_id_RENDEZ_VOUS FOREIGN KEY (id_RENDEZ_VOUS) REFERENCES RENDEZ_VOUS (id_RENDEZ_VOUS) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Possèder;
CREATE TABLE Possèder (
    id_USER INT NOT NULL,
    id_SPECIALISTE INT NOT NULL,
    dt_diplome_Possèder DATE,
    PRIMARY KEY (id_USER, id_SPECIALISTE),
    CONSTRAINT FK_Possèder_id_USER FOREIGN KEY (id_USER) REFERENCES USER (id_USER) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Possèder_id_SPECIALISTE FOREIGN KEY (id_SPECIALISTE) REFERENCES SPECIALITE (id_SPECIALISTE) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Localiser;
CREATE TABLE Localiser (
    id_ADRESSE INT NOT NULL AUTO_INCREMENT,
    id_USER INT NOT NULL,
    PRIMARY KEY (id_ADRESSE, id_USER),
    CONSTRAINT FK_Localiser_id_ADRESSE FOREIGN KEY (id_ADRESSE) REFERENCES ADRESSE (id_ADRESSE) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Localiser_id_USER FOREIGN KEY (id_USER) REFERENCES USER (id_USER) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE USER ADD CONSTRAINT dt_created_USER DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE RENDEZ_VOUS ADD CONSTRAINT dt_created_RENDEZ_VOUS DEFAULT CURRENT_TIMESTAMP();
